version: '3.8'
services:
  auth-redis:
    image: redis:6.2.6-alpine
    volumes:
      - auth_redis_data:/var/lib/redis/data
    restart: always

  auth-db:
    image: postgres:12
    env_file:
      - ./.env
    volumes:
      - auth_db_data:/var/lib/postgresql/data/
    restart: always

  auth:
    build:
      context: src/
      dockerfile: Dockerfile
    volumes:
      - ./src:/code
    env_file:
      - ./.env
    depends_on:
      - auth-db
      - auth-redis
    restart: always

volumes:
  auth_db_data:
  auth_redis_data:
