services:
  auth-redis:
    image: redis:6.2.6-alpine

  auth-db:
    image: postgres:14
    env_file:
      - ./.env

  auth:
    build:
      context: src/
      dockerfile: Dockerfile
    volumes:
      - ./src:/code
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - auth-db
      - auth-redis

  test:
    build:
      context: tests/functional/
      dockerfile: Dockerfile
    entrypoint: >
      sh -c "pytest /code/src"
    env_file:
      - ./.env
    volumes:
      - ./tests/functional:/code
    depends_on:
      - auth-redis
      - auth-db
      - auth