services:
  auth-redis:
    image: redis:6.2.6-alpine
    volumes:
      - auth_redis_data:/var/lib/redis/data
    networks:
      - movies_network
      - elk_stack

  auth-db:
    image: postgres:14
    env_file:
      - ./.env
    volumes:
      - auth_db_data:/var/lib/postgresql/data/
    networks:
      - movies_network
      - elk_stack

  auth-grpc:
    build:
      context: src/
      dockerfile: Dockerfile.grpc
    env_file:
      - ./.env
    volumes:
      - ./src:/code
    networks:
      - movies_network
      - elk_stack
    depends_on:
      - auth-db
      - auth

  auth:
    build:
      context: src/
      dockerfile: Dockerfile
    volumes:
      - ./src:/code
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - auth-db
      - auth-redis
    networks:
      - movies_network
      - elk_stack

  nginx-auth:
    image: nginx:1.19.2
    depends_on:
      - auth
      - auth-redis
      - auth-db
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx/configs:/etc/nginx/conf.d:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/logs/nginx/:/var/log/nginx/
#    restart: always
    networks:
      - movies_network
      - elk_stack

  jaeger:
    image: jaegertracing/all-in-one:0.8.0
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - movies_network
      - elk_stack

  filebeat-auth:
    image: docker.elastic.co/beats/filebeat:7.3.2
    volumes:
      - /tmp/logs/nginx:/var/log/nginx:ro
      - ./deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - auth
      - nginx-auth
    networks:
      - elk_stack
      - movies_network

volumes:
  auth_db_data:
  auth_redis_data:

networks:
  elk_stack:
    external: true
  movies_network:
    external: true
    name: movies_network
