services:
  auth-redis:
    image: redis:6.2.6-alpine
    volumes:
      - auth_redis_data:/var/lib/redis/data
    networks:
      - movies_network

  auth-db:
    image: postgres:14
    env_file:
      - ./.env
    volumes:
      - auth_db_data:/var/lib/postgresql/data/
    networks:
      - movies_network

  auth-grpc:
    build:
      context: src/
      dockerfile: Dockerfile.grpc
    image: recommendations
    env_file:
      - ./.env
    volumes:
      - ./src:/code
    networks:
      - movies_network
    depends_on:
      - auth-db
      - auth

  auth:
    build:
      context: src/
      dockerfile: Dockerfile
    volumes:
      - ./src:/code
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - auth-db
      - auth-redis
    networks:
      - movies_network

volumes:
  auth_db_data:
  auth_redis_data:

networks:
  movies_network:
    external: true
    name: movies_network
